tasks:
  - name: reminder - MUST use `gitpod-local-companion-darwin --mock-keyring=true`
    command: |
      echo '🚨 reminder - MUST use `gitpod-local-companion-darwin --mock-keyring=true`'
      echo '🚨 reminder - MUST use `gitpod-local-companion-darwin --mock-keyring=true`'
      echo '🚨 reminder - MUST use `gitpod-local-companion-darwin --mock-keyring=true`'
  - name: dev server part
    init: npm install -g json-server && npm install && gp sync-done installDone
    command: yarn run start 
    openMode: split-right
  # must cd into json-server directory!
  # and must wait above install json-server done
  - name: json server as BE 
    command: gp sync-await installDone && cd json-server && json-server --watch -p 3001 db.json
    openMode: split-right
ports:
  - port: 3000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - https://github.com/jimmygc/linenote-codelens/releases/download/1.0.1/linenote-codelens-1.0.1.vsix  